
export const LightPallete = {
  schemaName:               "light",
  blue:                     "#324A76", 
  blueNeon:                 "#1ED8D8", 
  red:                      "#ED3237", 
  black:                    "#252525", 
  yellow:                   "#FFE60A", 
  gray:                     "#C4C4C4", 
  white:                    "#FFFFFF", 
  whiteSmoke:               "#F4F5F8", 
  evaluationColor:          "#CBC4CC", 
  textColor:                "#FFFFFF", 
  concurrencyGreen:         "#17B41E", 
  concurrencyRed:           "#D7292D", 
  chartDatasetColor:        "#ED3238", 
  chartGradientFrom:        "#F3ECEC", 
  chartGradientTo:          "#FFFFFF", 
  chartColor:               "#620101", 
  chartLabelColor:          "#324A76", 
  chartDotColor:            "#830408", 
  chatOwnTextColor:         "#FFFFFF", 
  chatOwnBackgroundColor:   "#324A76", 
  chatTextColor:            "#676767", 
  chatTextBackgroundColor:  "#DBDBDB", 
  chatBackgroundColor:      "#E4E4E4"  
}
